name: flutter_map_example
description: Example application for 'flutter_map' package
publish_to: "none"
version: 6.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map:
  flutter_map_cancellable_tile_provider:
  latlong2: ^0.9.0
  proj4dart: ^2.1.0
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.1
  url_strategy: ^0.2.0
  http: ^1.1.0
  vector_math: ^2.1.2

dependency_overrides:
  flutter_map_cancellable_tile_provider:
  flutter_map:
    path: ../

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/map/anholt_osmbright/12/2177/
    - assets/map/anholt_osmbright/12/2178/
    - assets/map/anholt_osmbright/12/2179/
    - assets/map/anholt_osmbright/12/2180/
    - assets/map/anholt_osmbright/12/2181/
    - assets/map/anholt_osmbright/13/4354/
    - assets/map/anholt_osmbright/13/4355/
    - assets/map/anholt_osmbright/13/4356/
    - assets/map/anholt_osmbright/13/4357/
    - assets/map/anholt_osmbright/13/4358/
    - assets/map/anholt_osmbright/13/4359/
    - assets/map/anholt_osmbright/13/4360/
    - assets/map/anholt_osmbright/13/4361/
    - assets/map/anholt_osmbright/13/4362/
    - assets/map/anholt_osmbright/13/4363/
    - assets/map/anholt_osmbright/14/8709/
    - assets/map/anholt_osmbright/14/8710/
    - assets/map/anholt_osmbright/14/8711/
    - assets/map/anholt_osmbright/14/8712/
    - assets/map/anholt_osmbright/14/8713/
    - assets/map/anholt_osmbright/14/8714/
    - assets/map/anholt_osmbright/14/8715/
    - assets/map/anholt_osmbright/14/8716/
    - assets/map/anholt_osmbright/14/8717/
    - assets/map/anholt_osmbright/14/8718/
    - assets/map/anholt_osmbright/14/8719/
    - assets/map/anholt_osmbright/14/8720/
    - assets/map/anholt_osmbright/14/8721/
    - assets/map/anholt_osmbright/14/8722/
    - assets/map/anholt_osmbright/14/8723/
    - assets/map/anholt_osmbright/14/8724/
    - assets/map/anholt_osmbright/14/8725/
    - assets/map/anholt_osmbright/14/8726/
    - assets/map/anholt_osmbright/14/8727/
    - assets/map/epsg3413/amsr2.png
    - assets/mapbox-logo-white.png
    - assets/
