name: flutter_map
description: A versatile mapping package for Flutter, based off leaflet.js,
  that's simple and easy to learn, yet completely customizable and configurable.
version: 3.2.0
repository: https://github.com/fleaflet/flutter_map
issue_tracker: https://github.com/fleaflet/flutter_map/issues
documentation: https://docs.fleaflet.dev

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  async: ^2.9.0
  collection: ^1.16.0
  flutter:
    sdk: flutter
  http: ^0.13.5
  latlong2: ^0.8.0
  meta: ^1.8.0
  polylabel: ^1.0.1
  positioned_tap_detector_2: ^1.0.4
  proj4dart: ^2.1.0
  tuple: ^2.0.0
  vector_math: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: ^1.21.4
