name: flutter_map
description: A versatile mapping package for Flutter, that's simple and easy to learn, yet completely customizable and configurable
version: 7.0.2

repository: https://github.com/fleaflet/flutter_map
issue_tracker: https://github.com/fleaflet/flutter_map/issues
documentation: https://docs.fleaflet.dev

funding:
  - https://docs.fleaflet.dev/supporters#support-us

topics:
  - flutter-map
  - map

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  async: ^2.11.0
  collection: ^1.18.0
  dart_earcut: ^1.1.0
  flutter:
    sdk: flutter
  http: ^1.2.1
  latlong2: ^0.9.1
  logger: ^2.0.0
  meta: ^1.11.0
  polylabel: ^1.0.1
  proj4dart: ^2.1.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_lints: ">=4.0.0 <6.0.0"
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  test: ^1.24.9

flutter:
  assets:
    - lib/assets/flutter_map_logo.png
