name: flutter_map
description: A Dart implementation of Leaflet for Flutter apps
version: 0.12.0
repository: https://github.com/johnpryan/flutter_map

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.0
  latlong2: ^0.8.0
  positioned_tap_detector_2: ^1.0.0
  transparent_image: ^2.0.0
  async: ^2.5.0
  flutter_image: ^3.0.0
  vector_math: ^2.1.0
  proj4dart: ^2.0.0
  meta: ^1.3.0
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.0
  location: ^4.1.1
  flutter_test:
    sdk: flutter
  test: ^1.16.0 # due to recent dependency updates, an older version is used here
  mockito: ^5.0.5
