name: flutter_map
description: A flutter implementation of Leaflet
version: 0.0.3
authors:
- John Ryan <john.p.ryan4@gmail.com>
homepage: https://github.com/apptreesoftware/flutter_map

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  latlong: ^0.4.0
  tuple: ^1.0.0
  quiver: ^0.28.0

