name: flutter_map
description: A flutter implementation of Leaflet
version: 0.0.11+1
authors:
- John Ryan <john.p.ryan4@gmail.com>
homepage: https://github.com/apptreesoftware/flutter_map

environment:
  sdk: ">=1.19.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  latlong: ^0.5.3
  tuple: ^1.0.0
  transparent_image: ^0.1.0
