name: "'fleaflet/flutter_map' 'master' CI/CD"
on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: "Run Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Run Tests with Coverage
        run: flutter test -r expanded --coverage
      - name: Run Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build-android:
    name: "Build Android Example App"
    runs-on: ubuntu-latest
    needs: [ run-tests ]
    if: github.repository == 'fleaflet/flutter_map'
    defaults:
      run:
        working-directory: ./example
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Java 17 Environment
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Build Android Application
        run: flutter build apk
      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-build
          path: example/build/app/outputs/apk/release
          if-no-files-found: error

  build-windows:
    name: "Build Windows Example App"
    runs-on: windows-latest
    needs: [ run-tests ]
    if: github.repository == 'fleaflet/flutter_map'
    defaults:
      run:
        working-directory: ./example
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Build Windows Application
        run: flutter build windows
      - name: Create Windows Application Installer
        run: iscc "windowsApplicationInstallerSetup.iss"
        working-directory: .
      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe-build
          path: windowsTemp/WindowsApplication.exe
          if-no-files-found: error

  build-web:
    name: "Build & Deploy Web Example App"
    runs-on: ubuntu-latest
    needs: [ run-tests ]
    if: github.repository == 'fleaflet/flutter_map'
    defaults:
      run:
        working-directory: ./example
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Build Web Application
        run: flutter build web --web-renderer canvaskit
      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: example/build/web
          if-no-files-found: error
      - name: Publish Live Web App
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLEAFLET }}"
          channelId: live
          projectId: fleaflet-firebase